Repository googleapis/nodejs-containeranalysis, pull requests merged in 2019-05, with the labels that each got.

#3 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#5 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#6 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#4 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#1 refactor: add @google-cloud namespace
  .github/ISSUE_TEMPLATE/bug_report.md
  .jsdoc.js
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .nycrc
  README.md
  package.json
  src/index.js
  src/v1beta1/container_analysis_v1_beta1_client.js
  src/v1beta1/doc/google/protobuf/doc_any.js
  src/v1beta1/doc/google/protobuf/doc_field_mask.js
  src/v1beta1/doc/google/protobuf/doc_timestamp.js
  src/v1beta1/grafeas_v1_beta1_client.js
  synth.metadata
Labels: cla: yes

#8 feat: add doc expressions and update CI
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  package.json
  src/v1beta1/container_analysis_v1_beta1_client.js
  src/v1beta1/doc/google/iam/v1/doc_iam_policy.js
  src/v1beta1/doc/google/iam/v1/doc_policy.js
  src/v1beta1/doc/google/type/doc_expr.js
  synth.metadata
Labels: cla: yes

#15 build: update synth script and add infrastructure
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node11/common.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node11/common.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/release/publish.cfg
  README.md
  package.json
  protos/google/devtools/containeranalysis/v1beta1/build/build.proto
  samples/.eslintrc.yml
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/test/.eslintrc.yml
  samples/test/tests.js
  src/v1beta1/container_analysis_v1_beta1_client.js
  src/v1beta1/doc/grafeas/v1beta1/build/doc_build.js
  src/v1beta1/grafeas_v1_beta1_client.js
  synth.metadata
  synth.py
  system-test/system.js
  test/.eslintrc.yml
  test/gapic-v1beta1.js
Labels: cla: yes

#16 fix(docs): fix dead links
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  src/index.js
  src/v1beta1/container_analysis_v1_beta1_client.js
  src/v1beta1/grafeas_v1_beta1_client.js
  synth.metadata
  synth.py
Labels: cla: yes

#21 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#26 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1beta1/container_analysis_v1_beta1_client.js
  src/v1beta1/grafeas_v1_beta1_client.js
  synth.metadata
Labels: cla: yes

#27 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#28 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  package.json
Labels: cla: yes

#29 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#31 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
