Repository googleapis/nodejs-containeranalysis, pull requests merged in 2020-06, with the labels that each got.

#217 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#220 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/container_analysis_client.ts
  src/v1beta1/container_analysis_v1_beta1_client.ts
  src/v1beta1/grafeas_v1_beta1_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#223 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#224 test: attempt retry on note delete
  samples/test/containerAnalysis.test.js
Labels: automerge, cla: yes

#225 fix: handle fallback option properly
  src/v1/container_analysis_client.ts
  src/v1beta1/container_analysis_v1_beta1_client.ts
  src/v1beta1/grafeas_v1_beta1_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: none

#227 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#228 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
