Repository googleapis/nodejs-containeranalysis, pull requests merged in 2020-11, with the labels that each got.

#263 feat!: added getVulnerabilityOccurrencesSummary to v1
  .github/workflows/ci.yaml
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  package.json
  protos/google/cloud/common_resources.proto
  protos/google/devtools/containeranalysis/v1/containeranalysis.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v1/container_analysis_client.ts
  src/v1/container_analysis_client_config.json
  src/v1/grafeas_proto_list.json
  src/v1beta1/container_analysis_v1_beta1_client.ts
  src/v1beta1/container_analysis_v1_beta1_proto_list.json
  src/v1beta1/grafeas_v1_beta1_client.ts
  src/v1beta1/grafeas_v1_beta1_client_config.json
  src/v1beta1/grafeas_v1_beta1_proto_list.json
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_container_analysis_v1.ts
  test/gapic_container_analysis_v1_beta1_v1beta1.ts
  test/gapic_grafeas_v1_beta1_v1beta1.ts
Labels: api: containeranalysis, cla: yes

#262 docs(samples): update sample to illustrate AR style urls
  samples/createOccurrence.js
  samples/getDiscoveryInfo.js
  samples/highVulnerabilitiesForImage.js
  samples/occurrencesForImage.js
  samples/pollDiscoveryOccurrenceFinished.js
  samples/vulnerabilityOccurrencesForImage.js
Labels: api: containeranalysis, cla: yes, samples

#267 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/container_analysis_client.ts
  src/v1beta1/container_analysis_v1_beta1_client.ts
  src/v1beta1/grafeas_v1_beta1_client.ts
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: partial

#269 build: stop tracking generated files
  src/v1beta1/container_analysis_v1_beta1_client.ts
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: none

#270 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full
