Repository googleapis/nodejs-containeranalysis, pull requests merged in 2020-05, with the labels that each got.

#207 fix: remove unneeded common protos in generated proto list
  src/v1beta1/grafeas_v1_beta1_client.ts
  synth.metadata
  synth.py
  test/gapic_container_analysis_v1.ts
  test/gapic_container_analysis_v1_beta1_v1beta1.ts
Labels: cla: yes

#203 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#209 feat: check status of long running operation by its name
  synth.metadata
Labels: automerge, cla: yes

#212 docs: update import documentation in beta client
  src/v1beta1/grafeas_v1_beta1_client.ts
  synth.metadata
Labels: cla: yes, context: none

#213 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#214 fix: synth.py clean up for multiple version
  src/index.ts
  src/v1/index.ts
  src/v1beta1/grafeas_v1_beta1_client.ts
  src/v1beta1/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#216 docs: update library reference in jsdoc headers
  src/v1beta1/grafeas_v1_beta1_client.ts
  synth.metadata
Labels: cla: yes, context: none
